### ISSUE TITLE
Roadmap for public beta

### ISSUE THREAD

**Issue by eeeeeta** [eeeeeta/sqa#1]
SQA beta 1 will be released on or before 31 August, 2016. Here's a list of features I'd like to get done before that time (in no particular order):
- [x] **MP3 support, deprecating libsndfile**
- [ ] **Better error handling everywhere, and less `unwrap()`ping**
- [x] **Full cue support** - no threads, and ability to 'fall through' cues
  - [ ] More precise display/control of timing - show cue duration, etc
- [x] **Command editing and reordering** - all the hard UI stuff :(
- [ ] **Mixer & audio outputs** - control & wiring
- [ ] **Saving & loading** - basic serialisation of commands
- [ ] **Sleep/Wait command** - pauses cue execution for a set time
- [ ] **FIX ALL THE `/* FIXME */`s - and there are a lot of 'em**

Possibly more to follow.

**Comment by eeeeeta** [comment]
Hah. So much for this roadmap - only half the stuff got done! Anyway, it's release day now, so closing this for a rainy day sometime in the future...
